<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion><Nullable>enable</Nullable>
    <AssemblyName>KellysDOORMANStartup</AssemblyName><Version>1.3.4</Version>
    <NuGetAudit>false</NuGetAudit><RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Nuclear Option</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\src\ModData.cs" Link="ModData.cs" />
    <Compile Include="..\src\EmbeddedModPreview.cs" Link="EmbeddedModPreview.cs" />
    <Compile Include="..\src\ModImageHeader.cs" Link="ModImageHeader.cs" />
    <Compile Include="..\src\ModUpdateData.cs" Link="ModUpdateData.cs" />
    <Compile Include="..\src\ModUpdateFiles.cs" Link="ModUpdateFiles.cs" />
    <Compile Include="..\src\Diagnostics.cs" Link="Diagnostics.cs" />
    <Compile Include="..\src\ServerSetupData.cs" Link="ServerSetupData.cs" />
    <Compile Include="..\src\RestartStatus.cs" Link="RestartStatus.cs" />
    <Reference Include="BepInEx" HintPath="$(GameDir)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(GameDir)\BepInEx\core\0Harmony.dll" Private="false" />
    <Reference Include="Mono.Cecil" HintPath="$(GameDir)\BepInEx\core\Mono.Cecil.dll" Private="false" />
  </ItemGroup>
</Project>
